// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAOcZakbZsRIGo_1R7VmrKsKI8FuyAd2s',
    appId: '1:290388502384:web:8b9f02bf18cd9250f5d1b5',
    messagingSenderId: '290388502384',
    projectId: 'uploadscreen-e732c',
    authDomain: 'uploadscreen-e732c.firebaseapp.com',
    storageBucket: 'uploadscreen-e732c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL7gTmIDmZm5NRMyJhwhySDiU5SLi8j0c',
    appId: '1:290388502384:android:0cfddb20e1eb6608f5d1b5',
    messagingSenderId: '290388502384',
    projectId: 'uploadscreen-e732c',
    storageBucket: 'uploadscreen-e732c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNpyRyHhr7hfbRlOQZmfzVSpeVipqIJGs',
    appId: '1:290388502384:ios:30069fb10d22935bf5d1b5',
    messagingSenderId: '290388502384',
    projectId: 'uploadscreen-e732c',
    storageBucket: 'uploadscreen-e732c.appspot.com',
    iosClientId: '290388502384-s6iiab0nsghol1d36b2f2ptdc3h6g6q2.apps.googleusercontent.com',
    iosBundleId: 'com.deepeshkalura.uploadImage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNpyRyHhr7hfbRlOQZmfzVSpeVipqIJGs',
    appId: '1:290388502384:ios:30069fb10d22935bf5d1b5',
    messagingSenderId: '290388502384',
    projectId: 'uploadscreen-e732c',
    storageBucket: 'uploadscreen-e732c.appspot.com',
    iosClientId: '290388502384-s6iiab0nsghol1d36b2f2ptdc3h6g6q2.apps.googleusercontent.com',
    iosBundleId: 'com.deepeshkalura.uploadImage',
  );
}
